### ISSUE TITLE
IPv6 is not working for gRPC

### ISSUE THREAD

**Issue by mturkia** [strangelove-ventures/half-life#13]
Unable to use IPv6 for sentry monitoring. When giving address in form `[::1]:9090` I get following error message
```
2022/07/27 18:37:45 Error parsing config.yaml: yaml: line 109: did not find expected key
monitor.service: Main process exited, code=exited, status=1/FAILURE
monitor.service: Failed with result 'exit-code'.
```

If I give the address including protocol (`http://[::1]:9090`), getting following error
```
Got validator sentry errors: +[Monitor - rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address http://[::1]:9090: too many colons in address"]
```

**Comment by agouin** [comment]
Have you tried surrounding the input with quotes to make it valid yaml without the protocol? e.g. `grpc: "[::1]:9090"`. Without that, yaml is trying to handle the square brackets as an array.

**Comment by mturkia** [comment]
That was a simple fix. Tnx.
