### ISSUE TITLE
Request: Set the number of blocks to miss before alert

### ISSUE THREAD

**Issue by OtterSync** [strangelove-ventures/half-life#4]
Request: 
I would like to be able to set in the config the number of blocks a validator misses before an alert is placed in the channel. Ideally set per chain, or a global value. 

Reasoning: 
Some chains are less stable and the validator will miss a single block occasionally. It would be ideal to mitigate these alerts, and only be notified once there are X amount of missing blocks.

**Comment by agouin** [comment]
This can now be configured in `v0.2.0` on the config entries with `missed-blocks-threshold`. If not provided, it defaults to 0, so any missed blocks will trigger an alert.
